from __future__ import annotations

"""Shared helpers for validating and filtering AI-generated tags."""

import re
from typing import Iterable

# Tags that have proven to be unhelpful in practice when generated by AI models.
# These values should be expressed as kebab-case slugs to match downstream usage.
UNHELPFUL_TAG_SLUGS: set[str] = {
    "json",
    "tag",
    "tags",
    "user-support",
    "syncro-software",
    "booking-appointment",
    "hawkinsit-solutions",
    "normal",
}


def slugify_tag(value: str) -> str | None:
    """Convert raw tag text into a kebab-case slug."""

    if not value:
        return None
    lowered = value.lower()
    cleaned = re.sub(r"[^a-z0-9\s\-]+", "", lowered)
    cleaned = re.sub(r"\s+", "-", cleaned)
    cleaned = re.sub(r"-+", "-", cleaned).strip("-")
    if not cleaned:
        return None
    return cleaned[:48]


def _slug_body_length(slug: str) -> int:
    """Return the number of alphanumeric characters contained in a slug."""

    return sum(1 for char in slug if char.isalnum())


def is_helpful_slug(slug: str) -> bool:
    """Determine whether a slug represents a useful ticket tag."""

    if not slug:
        return False
    if slug in UNHELPFUL_TAG_SLUGS:
        return False
    if _slug_body_length(slug) < 3:
        return False
    if slug.replace("-", "").isdigit():
        return False
    return True


def filter_helpful_slugs(tags: Iterable[str]) -> list[str]:
    """Filter an iterable of slug strings down to helpful, unique tags."""

    filtered: list[str] = []
    seen: set[str] = set()
    for tag in tags:
        if not tag or not isinstance(tag, str):
            continue
        slug = tag.strip()
        if not slug:
            continue
        if not is_helpful_slug(slug):
            continue
        if slug in seen:
            continue
        filtered.append(slug)
        seen.add(slug)
    return filtered


def filter_helpful_texts(tags: Iterable[str]) -> list[str]:
    """Filter raw tag text values, preserving order and applying helpfulness rules."""

    filtered: list[str] = []
    seen: set[str] = set()
    for tag in tags:
        if not tag or not isinstance(tag, str):
            continue
        normalised = re.sub(r"\s+", " ", tag.strip().lower())
        if not normalised:
            continue
        slug = slugify_tag(normalised)
        if slug is None or not is_helpful_slug(slug):
            continue
        if slug in seen:
            continue
        filtered.append(normalised)
        seen.add(slug)
    return filtered
