from __future__ import annotations

"""Shared helpers for validating and filtering AI-generated tags."""

import re
import time
from collections import Counter
from importlib import import_module
from typing import Iterable

from app.core.database import db
from app.core.logging import log_error
from app.repositories import tag_exclusions as tag_exclusions_repo
from app.repositories import tag_synonyms as tag_synonyms_repo

# Tags that have proven to be unhelpful in practice when generated by AI models.
# These values should be expressed as kebab-case slugs to match downstream usage.
# This is the default set, but additional exclusions can be configured via the admin UI.
UNHELPFUL_TAG_SLUGS: set[str] = {
    "json",
    "tag",
    "tags",
    "user-support",
    "syncro-software",
    "booking-appointment",
    "hawkinsit-solutions",
    "normal",
}


async def get_all_excluded_tags() -> set[str]:
    """Get all excluded tags from both the default set and database."""
    db_exclusions = await tag_exclusions_repo.get_excluded_tag_slugs()
    return UNHELPFUL_TAG_SLUGS | db_exclusions


def slugify_tag(value: str) -> str | None:
    """Convert raw tag text into a kebab-case slug."""

    if not value:
        return None
    lowered = value.lower()
    cleaned = re.sub(r"[^a-z0-9\s\-]+", "", lowered)
    cleaned = re.sub(r"\s+", "-", cleaned)
    cleaned = re.sub(r"-+", "-", cleaned).strip("-")
    if not cleaned:
        return None
    return cleaned[:48]


def _slug_body_length(slug: str) -> int:
    """Return the number of alphanumeric characters contained in a slug."""

    return sum(1 for char in slug if char.isalnum())


def is_helpful_slug(slug: str, excluded_tags: set[str] | None = None) -> bool:
    """Determine whether a slug represents a useful ticket tag.
    
    Args:
        slug: The tag slug to check
        excluded_tags: Optional set of excluded tags. If None, uses UNHELPFUL_TAG_SLUGS only.
    """

    if not slug:
        return False
    # Use provided exclusions or fall back to default set
    exclusion_set = excluded_tags if excluded_tags is not None else UNHELPFUL_TAG_SLUGS
    if slug in exclusion_set:
        return False
    # Check if any excluded word appears as a component within the tag
    # Split by hyphens to get individual words in the slug
    slug_words = slug.split("-")
    for word in slug_words:
        if word in exclusion_set:
            return False
    if _slug_body_length(slug) < 3:
        return False
    if slug.replace("-", "").isdigit():
        return False
    return True


def filter_helpful_slugs(tags: Iterable[str], excluded_tags: set[str] | None = None) -> list[str]:
    """Filter an iterable of slug strings down to helpful, unique tags.
    
    Args:
        tags: Tags to filter
        excluded_tags: Optional set of excluded tags. If None, uses UNHELPFUL_TAG_SLUGS only.
    """

    filtered: list[str] = []
    seen: set[str] = set()
    for tag in tags:
        if not tag or not isinstance(tag, str):
            continue
        slug = tag.strip()
        if not slug:
            continue
        if not is_helpful_slug(slug, excluded_tags):
            continue
        if slug in seen:
            continue
        filtered.append(slug)
        seen.add(slug)
    return filtered


def filter_helpful_texts(tags: Iterable[str], excluded_tags: set[str] | None = None) -> list[str]:
    """Filter raw tag text values, preserving order and applying helpfulness rules.
    
    Args:
        tags: Tags to filter
        excluded_tags: Optional set of excluded tags. If None, uses UNHELPFUL_TAG_SLUGS only.
    """

    filtered: list[str] = []
    seen: set[str] = set()
    for tag in tags:
        if not tag or not isinstance(tag, str):
            continue
        normalised = re.sub(r"\s+", " ", tag.strip().lower())
        if not normalised:
            continue
        slug = slugify_tag(normalised)
        if slug is None or not is_helpful_slug(slug, excluded_tags):
            continue
        if slug in seen:
            continue
        filtered.append(normalised)
        seen.add(slug)
    return filtered


# ---------------------------------------------------------------------------
# Controlled tag vocabulary
# ---------------------------------------------------------------------------

# Vocabulary lookups run for every tagging request, so results are cached
# briefly; admin edits clear the cache immediately.
_VOCABULARY_CACHE_SECONDS = 300.0
PREFERRED_TAG_LIMIT = 40
PREFERRED_TAG_MIN_USES = 2
_PREFERRED_TAG_TICKET_SAMPLE = 2000
_MAX_SYNONYM_HOPS = 8

_synonym_cache: tuple[float, dict[str, str]] | None = None
_preferred_cache: tuple[float, list[str]] | None = None


def clear_tag_vocabulary_cache() -> None:
    """Drop cached synonyms and preferred tags so the next lookup reloads them."""

    global _synonym_cache, _preferred_cache
    _synonym_cache = None
    _preferred_cache = None


async def get_tag_synonym_map() -> dict[str, str]:
    """Return the ``{variant_slug: canonical_slug}`` synonym table."""

    global _synonym_cache
    now = time.monotonic()
    if _synonym_cache is not None and now - _synonym_cache[0] < _VOCABULARY_CACHE_SECONDS:
        return _synonym_cache[1]
    if not db.is_connected():
        return {}
    try:
        synonyms = await tag_synonyms_repo.get_synonym_map()
    except Exception as exc:  # pragma: no cover - defensive database guard
        log_error("Tag synonym lookup failed", error=str(exc))
        return {}
    _synonym_cache = (now, synonyms)
    return synonyms


def canonicalise_slug(slug: str, synonyms: dict[str, str]) -> str:
    """Follow the synonym table from ``slug`` to its canonical slug."""

    current = slug
    seen = {current}
    for _ in range(_MAX_SYNONYM_HOPS):
        target = synonyms.get(current)
        if not target or target in seen:
            break
        current = target
        seen.add(current)
    return current


def apply_tag_synonyms(tags: Iterable[str], synonyms: dict[str, str]) -> list[str]:
    """Map slug tags to their canonical slugs, de-duplicating in order."""

    merged: list[str] = []
    seen: set[str] = set()
    for tag in tags:
        if not tag or not isinstance(tag, str):
            continue
        slug = canonicalise_slug(tag.strip(), synonyms) if synonyms else tag.strip()
        if slug and slug not in seen:
            merged.append(slug)
            seen.add(slug)
    return merged


def canonicalise_tag_text(tag: str, synonyms: dict[str, str]) -> str:
    """Return display text for ``tag``, replaced by its canonical form if it is a variant."""

    slug = slugify_tag(tag)
    if not slug or not synonyms:
        return tag
    canonical = canonicalise_slug(slug, synonyms)
    if canonical == slug:
        return tag
    return canonical.replace("-", " ")


def apply_tag_text_synonyms(tags: Iterable[str], synonyms: dict[str, str]) -> list[str]:
    """Canonicalise display-text tags, de-duplicating on their slug form."""

    merged: list[str] = []
    seen: set[str] = set()
    for tag in tags:
        if not tag or not isinstance(tag, str):
            continue
        text = canonicalise_tag_text(tag, synonyms)
        slug = slugify_tag(text)
        if not slug or slug in seen:
            continue
        merged.append(text)
        seen.add(slug)
    return merged


def rank_preferred_tags(
    tag_lists: Iterable[Iterable[str]],
    synonyms: dict[str, str],
    excluded_tags: set[str],
    *,
    limit: int = PREFERRED_TAG_LIMIT,
    min_uses: int = PREFERRED_TAG_MIN_USES,
) -> list[str]:
    """Rank canonical tag slugs by how many tickets and articles use them."""

    counts: Counter[str] = Counter()
    for tags in tag_lists:
        slugs: set[str] = set()
        for tag in tags or []:
            slug = slugify_tag(str(tag))
            if not slug:
                continue
            slug = canonicalise_slug(slug, synonyms)
            if is_helpful_slug(slug, excluded_tags):
                slugs.add(slug)
        counts.update(slugs)
    ranked = sorted(
        (item for item in counts.items() if item[1] >= min_uses),
        key=lambda item: (-item[1], item[0]),
    )
    return [slug for slug, _ in ranked[:limit]]


async def get_preferred_tags(limit: int = PREFERRED_TAG_LIMIT) -> list[str]:
    """Return the most-used canonical tag slugs across tickets and articles."""

    global _preferred_cache
    now = time.monotonic()
    if _preferred_cache is not None and now - _preferred_cache[0] < _VOCABULARY_CACHE_SECONDS:
        return _preferred_cache[1][:limit]
    if not db.is_connected():
        return []
    try:
        synonyms = await get_tag_synonym_map()
        excluded = await get_all_excluded_tags()
        tag_lists = [
            *(await tag_synonyms_repo.list_recent_ticket_tags(_PREFERRED_TAG_TICKET_SAMPLE)),
            *(await tag_synonyms_repo.list_article_tags()),
        ]
    except Exception as exc:  # pragma: no cover - defensive database guard
        log_error("Preferred tag lookup failed", error=str(exc))
        return []
    preferred = rank_preferred_tags(tag_lists, synonyms, excluded)
    _preferred_cache = (now, preferred)
    return preferred[:limit]


def _replace_slug_tags(tags: list[str], variant: str, replacement: str) -> list[str] | None:
    """Swap tags whose slug is ``variant`` for ``replacement``; ``None`` if unchanged."""

    changed = False
    updated: list[str] = []
    seen: set[str] = set()
    for tag in tags:
        slug = slugify_tag(str(tag))
        value = str(tag)
        if slug == variant:
            value = replacement
            slug = slugify_tag(replacement)
            changed = True
        if slug and slug in seen:
            changed = True
            continue
        if slug:
            seen.add(slug)
        updated.append(value)
    return updated if changed else None


async def merge_existing_tags(variant_slug: str, canonical_slug: str) -> dict[str, int]:
    """Rewrite stored ticket and article tags from ``variant_slug`` to ``canonical_slug``.

    Ticket tags are stored as slugs and article tags as display text, so each
    keeps its own form. Changed sources are queued for RAG re-indexing at
    backfill priority so BM25 matching picks up the canonical tag.
    """

    rag_outbox = import_module("app.services.rag_outbox")
    variant_text = variant_slug.replace("-", " ")
    tickets_updated = 0
    for row in await tag_synonyms_repo.list_tickets_with_tag_text(variant_slug, variant_text):
        updated = _replace_slug_tags(row["ai_tags"], variant_slug, canonical_slug)
        if updated is None:
            continue
        await tag_synonyms_repo.set_ticket_tags(row["id"], updated)
        await rag_outbox.enqueue("tickets", row["id"], priority=rag_outbox.BACKFILL_PRIORITY)
        tickets_updated += 1

    articles_updated = 0
    canonical_text = canonical_slug.replace("-", " ")
    for row in await tag_synonyms_repo.list_articles_with_tag_text(variant_slug, variant_text):
        ai_tags = _replace_slug_tags(row["ai_tags"], variant_slug, canonical_text)
        manual_tags = _replace_slug_tags(row["manual_ai_tags"], variant_slug, canonical_text)
        if ai_tags is None and manual_tags is None:
            continue
        await tag_synonyms_repo.set_article_tags(
            row["id"],
            ai_tags if ai_tags is not None else row["ai_tags"],
            manual_tags if manual_tags is not None else row["manual_ai_tags"],
        )
        await rag_outbox.enqueue("knowledge_base", row["id"], priority=rag_outbox.BACKFILL_PRIORITY)
        articles_updated += 1

    clear_tag_vocabulary_cache()
    return {"tickets_updated": tickets_updated, "articles_updated": articles_updated}
