"""Test SMTP2Go tracking data storage in ticket_replies table."""

import pytest
from datetime import datetime, timezone


@pytest.mark.asyncio
async def test_record_email_sent_with_both_ids(monkeypatch):
    """Test that record_email_sent stores both tracking_id and smtp2go_message_id."""
    from app.services import smtp2go
    
    # Track database calls
    db_calls = []
    
    async def mock_execute(query, params):
        db_calls.append({'query': query, 'params': params})
        return 1
    
    # Mock database
    from app.core import database
    monkeypatch.setattr(database.db, "execute", mock_execute)
    
    # Call the function
    await smtp2go.record_email_sent(
        ticket_reply_id=110,
        tracking_id="VdqhOx5C0d-8C9fibiXYaL0Col4Zfo23rZorX8WmXas",
        smtp2go_message_id="1vNPyV-FnQW0hPy67Z-PAWN",
    )
    
    # Verify the database was updated
    assert len(db_calls) == 1
    call = db_calls[0]
    
    assert "UPDATE ticket_replies" in call['query']
    assert "email_tracking_id" in call['query']
    assert "smtp2go_message_id" in call['query']
    
    params = call['params']
    assert params['tracking_id'] == "VdqhOx5C0d-8C9fibiXYaL0Col4Zfo23rZorX8WmXas"
    assert params['smtp2go_message_id'] == "1vNPyV-FnQW0hPy67Z-PAWN"
    assert params['reply_id'] == 110
    assert 'sent_at' in params
    assert isinstance(params['sent_at'], datetime)


@pytest.mark.asyncio
async def test_record_email_sent_without_smtp2go_message_id(monkeypatch):
    """Test that record_email_sent works even without smtp2go_message_id."""
    from app.services import smtp2go
    
    db_calls = []
    
    async def mock_execute(query, params):
        db_calls.append({'query': query, 'params': params})
        return 1
    
    from app.core import database
    monkeypatch.setattr(database.db, "execute", mock_execute)
    
    # Call without smtp2go_message_id
    await smtp2go.record_email_sent(
        ticket_reply_id=42,
        tracking_id="test-tracking-id-123",
        smtp2go_message_id=None,  # Explicitly None
    )
    
    # Verify the database was updated
    assert len(db_calls) == 1
    call = db_calls[0]
    
    params = call['params']
    assert params['tracking_id'] == "test-tracking-id-123"
    assert params['smtp2go_message_id'] is None  # Should be NULL in database
    assert params['reply_id'] == 42


@pytest.mark.asyncio
async def test_smtp2go_response_normalization():
    """Test that SMTP2Go API responses are normalized correctly."""
    from app.services import smtp2go
    
    # Simulate the normalization logic for a response like in the problem statement
    result = {
        "recipients": ["customers@hawkinsit.au"],
        "subject": "RE: Ticket #110 - Customers Test",
        "smtp2go_message_id": "1vNPyV-FnQW0hPy67Z-PAWN",
        "tracking_id": "VdqhOx5C0d-8C9fibiXYaL0Col4Zfo23rZorX8WmXas"
    }
    
    # Simulate normalization (this is what happens in send_email_via_api)
    data = result.get("data") if isinstance(result, dict) else None
    if not isinstance(data, dict):
        data = result if isinstance(result, dict) else {}
    
    # Normalize message ID
    message_id = (
        data.get("smtp2go_message_id")
        or data.get("email_id")
        or data.get("message_id")
        or data.get("messageid")
        or data.get("request_id")
    )
    if message_id and not data.get("email_id"):
        data["email_id"] = message_id
    if message_id and not data.get("smtp2go_message_id"):
        data["smtp2go_message_id"] = message_id
    
    # Normalize tracking ID
    tracking_id = "generated-id"  # Would be generated by generate_tracking_id()
    response_tracking_id = data.get("tracking_id") or tracking_id
    if response_tracking_id and not data.get("tracking_id"):
        data["tracking_id"] = response_tracking_id
    
    # Verify normalization worked
    assert data["smtp2go_message_id"] == "1vNPyV-FnQW0hPy67Z-PAWN"
    assert data["tracking_id"] == "VdqhOx5C0d-8C9fibiXYaL0Col4Zfo23rZorX8WmXas"
    assert data["email_id"] == "1vNPyV-FnQW0hPy67Z-PAWN"


@pytest.mark.asyncio
async def test_smtp2go_response_with_data_envelope():
    """Test normalization when response is wrapped in a 'data' envelope."""
    # Some SMTP2Go responses have {"data": {...}}
    result = {
        "data": {
            "smtp2go_message_id": "wrapped-message-id",
            "tracking_id": "wrapped-tracking-id",
        }
    }
    
    # Simulate normalization
    data = result.get("data") if isinstance(result, dict) else None
    if not isinstance(data, dict):
        data = result if isinstance(result, dict) else {}
    
    message_id = (
        data.get("smtp2go_message_id")
        or data.get("email_id")
        or data.get("message_id")
    )
    if message_id and not data.get("email_id"):
        data["email_id"] = message_id
    if message_id and not data.get("smtp2go_message_id"):
        data["smtp2go_message_id"] = message_id
    
    tracking_id = "generated-id"
    response_tracking_id = data.get("tracking_id") or tracking_id
    if response_tracking_id and not data.get("tracking_id"):
        data["tracking_id"] = response_tracking_id
    
    assert data["smtp2go_message_id"] == "wrapped-message-id"
    assert data["tracking_id"] == "wrapped-tracking-id"
    assert data["email_id"] == "wrapped-message-id"


@pytest.mark.asyncio
async def test_smtp2go_response_with_email_id_only():
    """Test normalization when response only has email_id (not smtp2go_message_id)."""
    result = {
        "email_id": "only-email-id-123",
        "tracking_id": "test-tracking-id",
    }
    
    # Simulate normalization
    data = result.get("data") if isinstance(result, dict) else None
    if not isinstance(data, dict):
        data = result if isinstance(result, dict) else {}
    
    message_id = (
        data.get("smtp2go_message_id")
        or data.get("email_id")
        or data.get("message_id")
    )
    if message_id and not data.get("email_id"):
        data["email_id"] = message_id
    if message_id and not data.get("smtp2go_message_id"):
        data["smtp2go_message_id"] = message_id
    
    tracking_id = "generated-id"
    response_tracking_id = data.get("tracking_id") or tracking_id
    if response_tracking_id and not data.get("tracking_id"):
        data["tracking_id"] = response_tracking_id
    
    # Both should be set to the same value
    assert data["smtp2go_message_id"] == "only-email-id-123"
    assert data["email_id"] == "only-email-id-123"
    assert data["tracking_id"] == "test-tracking-id"
