-- Add reusable, current-company ticket-list searches to the Reporting catalogue.
-- Administrators can clone an example and replace the "search text" portion of
-- each LIKE pattern.  The surrounding % wildcards intentionally implement a
-- case-insensitive contains search under MyPortal's utf8mb4_unicode_ci collation.
INSERT IGNORE INTO reporting_queries (slug, name, description, sql_query, is_system)
VALUES
    ('tickets-search-subject', 'Tickets - Search Subject', 'Ticket list for the current company where the subject contains search text. Clone and replace "search text" in the LIKE pattern.', 'SELECT t.id AS ticket_id, t.subject, t.description AS initial_description, t.ai_tags, t.status, t.priority, t.created_at, t.updated_at FROM tickets t WHERE t.company_id = {{current.company}} AND COALESCE(t.subject, '''') LIKE ''%search text%'' ORDER BY t.updated_at DESC, t.id DESC', 1),
    ('tickets-search-initial-description', 'Tickets - Search Initial Description', 'Ticket list for the current company where the initial description contains search text. Clone and replace "search text" in the LIKE pattern.', 'SELECT t.id AS ticket_id, t.subject, t.description AS initial_description, t.ai_tags, t.status, t.priority, t.created_at, t.updated_at FROM tickets t WHERE t.company_id = {{current.company}} AND COALESCE(t.description, '''') LIKE ''%search text%'' ORDER BY t.updated_at DESC, t.id DESC', 1),
    ('tickets-search-ai-tags', 'Tickets - Search AI Tags', 'Ticket list for the current company where the AI tags contain search text. Clone and replace "search text" in the LIKE pattern.', 'SELECT t.id AS ticket_id, t.subject, t.description AS initial_description, t.ai_tags, t.status, t.priority, t.created_at, t.updated_at FROM tickets t WHERE t.company_id = {{current.company}} AND COALESCE(t.ai_tags, '''') LIKE ''%search text%'' ORDER BY t.updated_at DESC, t.id DESC', 1),
    ('tickets-search-subject-and-description', 'Tickets - Search Subject AND Initial Description', 'Ticket list for the current company where both subject and initial description contain their specified text. Clone and replace each labelled search value.', 'SELECT t.id AS ticket_id, t.subject, t.description AS initial_description, t.ai_tags, t.status, t.priority, t.created_at, t.updated_at FROM tickets t WHERE t.company_id = {{current.company}} AND COALESCE(t.subject, '''') LIKE ''%subject text%'' AND COALESCE(t.description, '''') LIKE ''%description text%'' ORDER BY t.updated_at DESC, t.id DESC', 1),
    ('tickets-search-subject-and-ai-tags', 'Tickets - Search Subject AND AI Tags', 'Ticket list for the current company where both subject and AI tags contain their specified text. Clone and replace each labelled search value.', 'SELECT t.id AS ticket_id, t.subject, t.description AS initial_description, t.ai_tags, t.status, t.priority, t.created_at, t.updated_at FROM tickets t WHERE t.company_id = {{current.company}} AND COALESCE(t.subject, '''') LIKE ''%subject text%'' AND COALESCE(t.ai_tags, '''') LIKE ''%tag text%'' ORDER BY t.updated_at DESC, t.id DESC', 1),
    ('tickets-search-description-and-ai-tags', 'Tickets - Search Initial Description AND AI Tags', 'Ticket list for the current company where both initial description and AI tags contain their specified text. Clone and replace each labelled search value.', 'SELECT t.id AS ticket_id, t.subject, t.description AS initial_description, t.ai_tags, t.status, t.priority, t.created_at, t.updated_at FROM tickets t WHERE t.company_id = {{current.company}} AND COALESCE(t.description, '''') LIKE ''%description text%'' AND COALESCE(t.ai_tags, '''') LIKE ''%tag text%'' ORDER BY t.updated_at DESC, t.id DESC', 1),
    ('tickets-search-all-fields-and', 'Tickets - Search Subject AND Description AND AI Tags', 'Ticket list for the current company where subject, initial description, and AI tags all contain their specified text. Clone and replace each labelled search value.', 'SELECT t.id AS ticket_id, t.subject, t.description AS initial_description, t.ai_tags, t.status, t.priority, t.created_at, t.updated_at FROM tickets t WHERE t.company_id = {{current.company}} AND COALESCE(t.subject, '''') LIKE ''%subject text%'' AND COALESCE(t.description, '''') LIKE ''%description text%'' AND COALESCE(t.ai_tags, '''') LIKE ''%tag text%'' ORDER BY t.updated_at DESC, t.id DESC', 1),
    ('tickets-search-subject-or-description', 'Tickets - Search Subject OR Initial Description', 'Ticket list for the current company where subject or initial description contains search text. Clone and replace "search text" in both LIKE patterns.', 'SELECT t.id AS ticket_id, t.subject, t.description AS initial_description, t.ai_tags, t.status, t.priority, t.created_at, t.updated_at FROM tickets t WHERE t.company_id = {{current.company}} AND (COALESCE(t.subject, '''') LIKE ''%search text%'' OR COALESCE(t.description, '''') LIKE ''%search text%'') ORDER BY t.updated_at DESC, t.id DESC', 1),
    ('tickets-search-subject-or-ai-tags', 'Tickets - Search Subject OR AI Tags', 'Ticket list for the current company where subject or AI tags contain search text. Clone and replace "search text" in both LIKE patterns.', 'SELECT t.id AS ticket_id, t.subject, t.description AS initial_description, t.ai_tags, t.status, t.priority, t.created_at, t.updated_at FROM tickets t WHERE t.company_id = {{current.company}} AND (COALESCE(t.subject, '''') LIKE ''%search text%'' OR COALESCE(t.ai_tags, '''') LIKE ''%search text%'') ORDER BY t.updated_at DESC, t.id DESC', 1),
    ('tickets-search-description-or-ai-tags', 'Tickets - Search Initial Description OR AI Tags', 'Ticket list for the current company where initial description or AI tags contain search text. Clone and replace "search text" in both LIKE patterns.', 'SELECT t.id AS ticket_id, t.subject, t.description AS initial_description, t.ai_tags, t.status, t.priority, t.created_at, t.updated_at FROM tickets t WHERE t.company_id = {{current.company}} AND (COALESCE(t.description, '''') LIKE ''%search text%'' OR COALESCE(t.ai_tags, '''') LIKE ''%search text%'') ORDER BY t.updated_at DESC, t.id DESC', 1),
    ('tickets-search-all-fields-or', 'Tickets - Search Subject OR Description OR AI Tags', 'Ticket list for the current company where subject, initial description, or AI tags contain search text. Clone and replace "search text" in all LIKE patterns.', 'SELECT t.id AS ticket_id, t.subject, t.description AS initial_description, t.ai_tags, t.status, t.priority, t.created_at, t.updated_at FROM tickets t WHERE t.company_id = {{current.company}} AND (COALESCE(t.subject, '''') LIKE ''%search text%'' OR COALESCE(t.description, '''') LIKE ''%search text%'' OR COALESCE(t.ai_tags, '''') LIKE ''%search text%'') ORDER BY t.updated_at DESC, t.id DESC', 1);
