-- phase: data
-- compatible-from: *
-- compatible-to: *
-- maintenance: false
-- Repair Company Overview report queries seeded by 316 that reference columns
-- which do not exist (staff.name, staff.position, licenses.notes and an ORDER BY
-- on subscriptions.product_name). Only rows still holding the original seeded
-- SQL are updated so administrator edits are preserved.
UPDATE reporting_queries SET sql_query = 'SELECT s.id, CONCAT_WS('' '', s.first_name, s.last_name) AS name, s.email, s.department, s.job_title, s.mobile_phone, s.onboarding_status, s.m365_last_sign_in FROM staff s WHERE s.company_id = {{current.company}} AND s.enabled = 1 AND NOT (LOWER(SUBSTR(s.email, 1, 8)) = ''package_'') ORDER BY LOWER(s.last_name), LOWER(s.first_name), LOWER(s.email)' WHERE slug = 'report-active-staff' AND sql_query = 'SELECT s.id, COALESCE(NULLIF(s.name, ''''), CONCAT_WS('' '', s.first_name, s.last_name)) AS name, s.email, s.department, COALESCE(s.position, s.job_title) AS job_title, s.mobile_phone, s.onboarding_status, s.m365_last_sign_in FROM staff s WHERE s.company_id = {{current.company}} AND s.enabled = 1 AND NOT (LOWER(SUBSTR(s.email, 1, 8)) = ''package_'') ORDER BY LOWER(s.last_name), LOWER(s.first_name), LOWER(s.email)';
UPDATE reporting_queries SET sql_query = 'SELECT s.id, CONCAT_WS('' '', s.first_name, s.last_name) AS name, s.email, s.department, s.job_title, s.mobile_phone, s.onboarding_status, s.m365_last_sign_in FROM staff s WHERE s.company_id = {{current.company}} AND s.enabled = 1 AND NOT (LOWER(SUBSTR(s.email, 1, 8)) = ''package_'') ORDER BY LOWER(s.last_name), LOWER(s.first_name), LOWER(s.email)' WHERE slug = 'report-active-user-accounts' AND sql_query = 'SELECT s.id, COALESCE(NULLIF(s.name, ''''), CONCAT_WS('' '', s.first_name, s.last_name)) AS name, s.email, s.department, COALESCE(s.position, s.job_title) AS job_title, s.mobile_phone, s.onboarding_status, s.m365_last_sign_in FROM staff s WHERE s.company_id = {{current.company}} AND s.enabled = 1 AND NOT (LOWER(SUBSTR(s.email, 1, 8)) = ''package_'') ORDER BY LOWER(s.last_name), LOWER(s.first_name), LOWER(s.email)';
UPDATE reporting_queries SET sql_query = 'SELECT l.id, COALESCE(lsn.friendly_name, app.name, l.name) AS license_name, l.count AS total_seats, (SELECT COUNT(DISTINCT sl.staff_id) FROM staff_licenses sl WHERE sl.license_id = l.id) AS allocated_seats, GREATEST(l.count - (SELECT COUNT(DISTINCT sl.staff_id) FROM staff_licenses sl WHERE sl.license_id = l.id), 0) AS available_seats, l.expiry_date, l.auto_renew, l.contract_term FROM licenses l LEFT JOIN apps app ON app.vendor_sku = l.platform LEFT JOIN license_sku_friendly_names lsn ON lsn.sku = l.platform WHERE l.company_id = {{current.company}} ORDER BY license_name ASC' WHERE slug = 'report-licenses' AND sql_query = 'SELECT l.id, COALESCE(lsn.friendly_name, app.name, l.name) AS license_name, l.count AS total_seats, (SELECT COUNT(DISTINCT sl.staff_id) FROM staff_licenses sl WHERE sl.license_id = l.id) AS allocated_seats, GREATEST(l.count - (SELECT COUNT(DISTINCT sl.staff_id) FROM staff_licenses sl WHERE sl.license_id = l.id), 0) AS available_seats, l.expiry_date, l.auto_renew, l.notes FROM licenses l LEFT JOIN apps app ON app.vendor_sku = l.platform LEFT JOIN license_sku_friendly_names lsn ON lsn.sku = l.platform WHERE l.company_id = {{current.company}} ORDER BY license_name ASC';
UPDATE reporting_queries SET sql_query = 'SELECT s.id AS subscription_id, COALESCE(p.name, s.external_name) AS product_name, c.name AS category_name, s.quantity, s.status, s.start_date, s.end_date, s.unit_price, s.auto_renew FROM subscriptions s LEFT JOIN shop_products p ON p.id = s.product_id LEFT JOIN subscription_categories c ON c.id = s.subscription_category_id WHERE s.customer_id = {{current.company}} ORDER BY s.status ASC, product_name ASC' WHERE slug = 'report-subscriptions' AND sql_query = 'SELECT s.id AS subscription_id, p.name AS product_name, c.name AS category_name, s.quantity, s.status, s.start_date, s.end_date, s.unit_price, s.auto_renew FROM subscriptions s LEFT JOIN shop_products p ON p.id = s.product_id LEFT JOIN subscription_categories c ON c.id = s.subscription_category_id WHERE s.customer_id = {{current.company}} ORDER BY s.status ASC, s.product_name ASC';
